loadClazz([{
	"clazzId":"2001",
	"clazzName":"一年一班",
	"clazzNums":"44",
	"clazzTeacher":"Larry",
	"clazzMonitor":"Mark",
	"g_id":"1001"
},{
	"clazzId":"2002",
	"clazzName":"一年二班",
	"clazzNums":"45",
	"clazzTeacher":"Terry",
	"clazzMonitor":"Mark",
	"g_id":"1002"
},{
	"clazzId":"2003",
	"clazzName":"一年三班",
	"clazzNums":"46",
	"clazzTeacher":"Marry",
	"clazzMonitor":"Mark",
	"g_id":"1002"
},{
	"clazzId":"2004",
	"clazzName":"二年一班",
	"clazzNums":"47",
	"clazzTeacher":"Horry",
	"clazzMonitor":"Mark",
	"g_id":"1003"
}])