loadStudent([{
	"studentId":"1001",
	"studentName":"张三",
	"studentClazz":"一年一班",
	"studentGender":"男",
	"studentScore":"85",	
	"c_id":"2001"
},{
	"studentId":"1002",
	"studentName":"李四",
	"studentClazz":"二年二班",
	"studentGender":"男",
	"studentScore":"56",	
	"c_id":"2002"
},{
	"studentId":"1003",
	"studentName":"王五",
	"studentClazz":"三年三班",
	"studentGender":"女",
	"studentScore":"84",	
	"c_id":"2003"
},{
	"studentId":"1004",
	"studentName":"赵六",
	"studentClazz":"四年四班",
	"studentGender":"男",
	"studentScore":"55",	
	"c_id":"2004"
},{
	"studentId":"1005",
	"studentName":"孙七",
	"studentClazz":"五年五班",
	"studentGender":"男",
	"studentScore":"87",	
	"c_id":"2005"
}])